//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCConsultant
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingSeat
    {
        public int AccountingSeatID { get; set; }
        public int SuplierID { get; set; }
        public int DocTypeID { get; set; }
        public System.DateTime AccountingSeatDate { get; set; }
        public decimal AccountingSeatAmount { get; set; }
        public bool AccountingSeatStatus { get; set; }
    
        public virtual DocType DocType { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
