//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCConsultant
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReceivableAccountsEntities : DbContext
    {
        public ReceivableAccountsEntities()
            : base("name=ReceivableAccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountingSeat> AccountingSeat { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<DocType> DocType { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
    }
}
