//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CXCConsultant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public string TransactionMovementType { get; set; }
        public int DocTypeID { get; set; }
        public int TransactionDocID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int CustomerID { get; set; }
        public decimal TransactionAmount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DocType DocType { get; set; }
    }
}
